### ISSUE TITLE
Enable wiki or discussions for people to share examples and related useful libraries?

### ISSUE THREAD

**Issue by jedahan** [klayveR/poe-api-wrappers#10]
I've been spending a bit of time looking at client-side ratelimiting libraries, and would like to share them. Wiki or Discussions might be a good place for people to share that stuff.

**Comment by klayveR** [comment]
Today I learned GitHub added discussions, looks neat. I've enabled them, would love to discuss rate limiting solutions as I've been looking for a good library for a while without success.
